import type { DeployableModule, DeploymentConfig } from '../engine';

export class CICDGenerator {
  generate(config: DeploymentConfig): DeployableModule[] {
    return [
      this.generateGitHubActions(config),
      this.generateDependabot(config),
    ];
  }

  private generateGitHubActions(config: DeploymentConfig): DeployableModule {
    const env = config.environment;
    const region = config.region ?? 'us-east-1';

    return {
      path: '.github/workflows/deploy.yml',
      content: `# Generated by Genesis-1 Deployment Engine
name: Deploy to ${env}

on:
  push:
    branches: [${env === 'production' ? 'main' : env}]
  workflow_dispatch:

concurrency:
  group: deploy-${env}
  cancel-in-progress: false

env:
  AWS_REGION: ${region}
  ECR_REPOSITORY: genesis-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run build

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::\\\${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy
          aws-region: \\\${{ env.AWS_REGION }}
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        run: |
          docker build -t \\\${{ env.ECR_REPOSITORY }}:\\\${{ github.sha }} .
          docker tag \\\${{ env.ECR_REPOSITORY }}:\\\${{ github.sha }} \\\${{ env.ECR_REPOSITORY }}:${env}
          docker push \\\${{ env.ECR_REPOSITORY }}:\\\${{ github.sha }}
          docker push \\\${{ env.ECR_REPOSITORY }}:${env}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Apply
        run: |
          cd terraform
          terraform init -backend-config="key=${env}/terraform.tfstate"
          terraform apply -auto-approve -var="environment=${env}"
      - name: Update ECS service
        run: |
          aws ecs update-service \\
            --cluster genesis-${env}-cluster \\
            --service genesis-app \\
            --force-new-deployment \\
            --region \\\${{ env.AWS_REGION }}
      - name: Health check
        run: |
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://api.${config.domain ?? 'app.example.com'}/health)
            if [ "$STATUS" == "200" ]; then exit 0; fi
            sleep 10
          done
          exit 1

  rollback:
    if: failure()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Rollback deployment
        run: |
          echo "Deployment failed — triggering rollback"
          aws ecs update-service \\
            --cluster genesis-${env}-cluster \\
            --service genesis-app \\
            --task-definition genesis-app-previous \\
            --region \\\${{ env.AWS_REGION }}
`,
      language: 'yaml', type: 'cicd', description: `CI/CD pipeline for ${env}`,
    };
  }

  private generateDependabot(config: DeploymentConfig): DeployableModule {
    return {
      path: '.github/dependabot.yml',
      content: `version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "automated"
`,
      language: 'yaml', type: 'cicd', description: 'Dependabot configuration',
    };
  }
}
