import type { GraphNode } from '@genesis-1/shared';
import type { DeployableModule, DeploymentConfig } from '../engine';

export class DockerGenerator {
  generate(nodes: GraphNode[], config: DeploymentConfig): DeployableModule[] {
    const modules: DeployableModule[] = [];
    const services = nodes.filter((n) =>
      ['service', 'function', 'container', 'api_gateway', 'pod'].includes(n.type),
    );

    // Root docker-compose
    modules.push(this.generateCompose(nodes, config));

    // Per-service Dockerfile
    for (const svc of services) {
      modules.push(this.generateServiceDockerfile(svc, config));
    }

    // .dockerignore
    modules.push({
      path: '.dockerignore',
      content: `node_modules\n.next\ndist\n.git\n*.log\n.env.local\ncoverage\n`,
      language: 'dockerfile',
      type: 'docker',
      description: 'Docker ignore rules',
    });

    return modules;
  }

  private generateCompose(nodes: GraphNode[], config: DeploymentConfig): DeployableModule {
    const services = nodes.filter((n) =>
      ['service', 'function', 'container', 'api_gateway', 'database', 'cache', 'queue'].includes(n.type),
    );

    const serviceEntries = services.map((svc) => {
      const name = svc.name.toLowerCase().replace(/\s+/g, '-');
      const port = (svc.runtime as Record<string, unknown>)?.port ?? 3000;
      const memory = (svc.runtime as Record<string, unknown>)?.memory ?? '256Mi';
      const cpu = (svc.runtime as Record<string, unknown>)?.cpu ?? '0.5';

      return `  ${name}:
    build:
      context: ./${name}
      dockerfile: Dockerfile
    ports:
      - "${port}:${port}"
    environment:
      - NODE_ENV=${config.environment}
    ${svc.deployment && (svc.deployment as Record<string, unknown>).resources ? `deploy:
      resources:
        limits:
          cpus: '${cpu}'
          memory: '${memory}'` : ''}
    restart: ${config.environment === 'production' ? 'always' : 'unless-stopped'}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${port}/health"]
      interval: 30s
      timeout: 5s
      retries: 3`;
    });

    const dbEntries = services.filter((n) => ['database', 'cache', 'queue'].includes(n.type)).map((n) => {
      const name = n.name.toLowerCase().replace(/\s+/g, '-');
      if (n.type === 'database') {
        return `  ${name}:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: \${DB_PASSWORD}
    volumes:
      - ${name}_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5`;
      }
      if (n.type === 'cache') {
        return `  ${name}:
    image: redis:7-alpine
    volumes:
      - ${name}_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5`;
      }
      return '';
    }).filter(Boolean);

    const volumes = services.filter((n) => ['database', 'cache'].includes(n.type)).map((n) =>
      `  ${n.name.toLowerCase().replace(/\s+/g, '-')}_data:`).join('\n');

    return {
      path: 'docker-compose.yml',
      content: `# Generated by Genesis-1 Deployment Engine
# Environment: ${config.environment}
# Generated for ${services.length} services

services:
${serviceEntries.join('\n\n')}

${dbEntries.length > 0 ? `\n${dbEntries.join('\n\n')}\n` : ''}
${volumes ? `volumes:\n${volumes}` : ''}`,
      language: 'yaml',
      type: 'docker',
      description: `Docker Compose for ${config.environment}`,
    };
  }

  private generateServiceDockerfile(svc: GraphNode, config: DeploymentConfig): DeployableModule {
    const name = svc.name.toLowerCase().replace(/\s+/g, '-');
    const port = (svc.runtime as Record<string, unknown>)?.port ?? 3000;

    return {
      path: `${name}/Dockerfile`,
      content: `# Generated for ${svc.name}
# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --only=production && npm cache clean --force

# Stage 2: Runtime
FROM node:20-alpine AS runner
RUN addgroup --system --gid 1001 app && adduser --system --uid 1001 app
WORKDIR /app
COPY --from=builder --chown=app:app /app/node_modules ./node_modules
COPY --chown=app:app . .
USER app
EXPOSE ${port}
HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD wget -q --spider http://localhost:${port}/health || exit 1
CMD ["node", "dist/index.js"]`,
      language: 'dockerfile',
      type: 'docker',
      description: `Dockerfile for ${svc.name}`,
    };
  }
}
